// <auto-generated />
namespace EventSwift.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SubmittedAt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubmittedAt));
        
        string IMigrationMetadata.Id
        {
            get { return "202512110333020_SubmittedAt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
